name: Test and Publish to NPM
on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies and build 🔧
        run: yarn install --frozen-lockfile 
      - name: test install
        run: if [[ -e /path/to/file.txt ]]; then
              echo "File exists."
             else
              echo "File does not exist."
             fi
      - name: Test
        run: yarn test --run
      
      
